import React,{useState} from 'react';
import {api} from '../api';
const rate=s=>s?.accuracy==null?'—':`${(s.accuracy*100).toFixed(1)}% · n=${s.n} (${s.unique_cases} cases)`;
const labels=['WRONG_TABLE','BAD_JOIN','WRONG_FILTER','WRONG_AGGREGATION','DIALECT_ERROR','HALLUCINATED_COLUMN','VALIDATOR_BLOCK','GAVE_UP','UNEXPECTED_REFUSAL','MISSED_REFUSAL','MISSING_ASSUMPTION','RESULT_MISMATCH','INVALID_REFERENCE'];

export function FailureEditor({runId,profile,observation,onSaved}){
 const [label,setLabel]=useState(observation.manual_failure_label||observation.failure_label||'RESULT_MISMATCH');
 const [reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function save(e){e.preventDefault();setBusy(true);try{await api(`/evaluation/runs/${runId}/override`,{method:'POST',body:{profile,case_id:observation.case_id,repeat:observation.repeat||1,label,reason}});onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <form onSubmit={save}><p>Automatic diagnosis: {observation.failure_label||observation.failure}. This is a heuristic, not proof of cause.</p><pre>{JSON.stringify(observation.diagnostic_evidence,null,2)}</pre><label>Manual diagnostic label<select value={label} onChange={e=>setLabel(e.target.value)}>{labels.map(x=><option key={x}>{x}</option>)}</select></label><label>Reason<input required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="secondary" disabled={busy}>Save label override</button>{error&&<p role="alert" className="error">{error}</p>}<p className="field-hint">Relabeling changes diagnostic counts; it never changes pass/fail or accuracy.</p></form>
}

export default function BenchmarkDetails({report,runs,onError}){
 const [old,setOld]=useState(''),[margin,setMargin]=useState(5),[diff,setDiff]=useState(null),[message,setMessage]=useState('');
 async function baseline(){try{await api(`/evaluation/runs/${report.run_id}/baseline`,{method:'POST',body:{margin:Number(margin)/100}});setMessage('Saved as baseline. Future comparable runs will be checked.')}catch(e){onError(e.message)}}
 async function compare(){try{setDiff(await api(`/evaluation/compare?old=${encodeURIComponent(old)}&new=${encodeURIComponent(report.run_id)}&margin=${Number(margin)/100}`))}catch(e){onError(e.message)}}
 const profiles=Object.entries(report.profiles),tiers=[...new Set(profiles.flatMap(([,p])=>Object.keys(p.metrics.by_tier||{})))];
 return <><h3>Accuracy by tier</h3><div style={{overflowX:'auto'}}><table className="eval-table"><thead><tr><th>Tier</th>{profiles.map(([name])=><th key={name}>{name}</th>)}</tr></thead><tbody>{tiers.map(t=><tr key={t}><td>{t}</td>{profiles.map(([name,p])=><td key={name}>{p.metrics.by_tier?.[t]?.answer?<>Answer {rate(p.metrics.by_tier[t].answer)}<br/>Safety {rate(p.metrics.by_tier[t].safety)}</>:rate(p.metrics.by_tier?.[t])}</td>)}</tr>)}</tbody></table></div>
 {profiles.map(([name,p])=><details key={name}><summary>{name}: repeat consistency and separate latency</summary><p>Answer: {rate(p.metrics.answer)} · Safety: {rate(p.metrics.safety)} · Overall: {rate(p.metrics.overall)}</p><p>Answer accuracy mean: {p.metrics.answer_accuracy_mean==null?'—':(p.metrics.answer_accuracy_mean*100).toFixed(1)+'%'}; standard deviation: {p.metrics.answer_accuracy_stddev==null?'—':(p.metrics.answer_accuracy_stddev*100).toFixed(2)+' percentage points'}. Repeats are correlated.</p><pre>{JSON.stringify({repeat_consistency:p.metrics.repeat_breakdown,answer_latency:p.metrics.answer_latency,refusal_latency:p.metrics.refusal_latency,failure_labels:p.metrics.failure_labels},null,2)}</pre></details>)}
 <h3>Baseline and run comparison</h3><label>Regression margin (percentage points)<input type="number" min={0} max={100} step={1} value={margin} onChange={e=>setMargin(e.target.value)}/></label><button className="secondary" onClick={baseline}>Use this run as baseline</button>{message&&<p className="success">{message}</p>}<label>Compare previous run<select value={old} onChange={e=>setOld(e.target.value)}><option value="">Choose a completed run</option>{runs.filter(r=>r.status==='completed'&&r.id!==report.run_id).map(r=><option key={r.id} value={r.id}>{new Date(r.created_at).toLocaleString()}</option>)}</select></label><button className="secondary" disabled={!old} onClick={compare}>Compare with selected run</button>{(diff||report.baseline_comparison)&&<pre>{JSON.stringify(diff||report.baseline_comparison,null,2)}</pre>}
 <details><summary>Safety layers: guard, validator, database</summary><pre>{JSON.stringify(report.safety_layers,null,2)}</pre></details><details><summary>Reference verification and repeatability</summary><p>Temperature {report.temperature}; seed {report.seed}; repeats {report.repeats}. Warm-up excluded. p95 requires 30 samples in its latency group.</p><p>Data fingerprint: <code>{report.data_fingerprint}</code></p><p>Source dialect: {report.source_dialect}; evaluation dialect: {report.execution_dialect}.</p><pre>{JSON.stringify(report.reference_verification,null,2)}</pre></details></>
}
