import React,{useState} from 'react';
import {Database,Upload,ArrowUpRight,Plus,FileSpreadsheet,HardDrive,ShieldCheck} from 'lucide-react';
import {api} from '../api';
import Modal from './Modal';

export default function DatasetManager({datasets,onSelect,onChanged,roots}){
 const [dialog,setDialog]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({name:'',kind:'mysql',host:'127.0.0.1',port:3306,database:'',username:'',password:'',path:''});
 const [file,setFile]=useState(null),[name,setName]=useState(''),[dialect,setDialect]=useState('mysql');
 const update=(key,value)=>setForm({...form,[key]:value});
 const open=mode=>{setError('');setDialog(mode);setFile(null);setName('')};
 async function submit(e){e.preventDefault();setError('');setBusy(true);try{
  let data;
  if(dialog==='connect')data=await api('/datasets/connect',{method:'POST',body:form});
  else{if(!file)throw Error('Choose a CSV or SQL file.');data=await api('/datasets/upload?'+new URLSearchParams({name:name.trim(),filename:file.name,dialect}),{method:'POST',body:file,raw:true})}
  await onChanged();onSelect(data.id,'schema');setDialog(null);
 }catch(e){setError(e.message)}finally{setBusy(false)}}
 return <><div className="page-heading"><div><span className="eyebrow">YOUR DATA, UNDER ONE ROOF</span><h1>A workspace for every dataset.</h1><p>Connect a local database or bring a file. Explore each source with its own schema and access policy.</p></div><div className="heading-actions"><button className="secondary" onClick={()=>open('connect')}><Plus size={17}/> Connect database</button><button className="primary" onClick={()=>open('upload')}><Upload size={17}/> Import file</button></div></div>
 <div className="stats-row"><div><span>Connected datasets</span><strong>{datasets.length}</strong></div><div><span>Discoverable tables</span><strong>{datasets.reduce((n,d)=>n+d.table_count,0)}</strong></div><div><span>Inference</span><strong className="small-stat">Local only</strong></div></div>
 <div className="section-heading"><h2>Dataset library</h2><span>{datasets.length} sources</span></div>
 {datasets.length?<div className="dataset-grid">{datasets.map(d=><button className="dataset-card" key={d.id} onClick={()=>onSelect(d.id,'analyst')}><div className="card-top"><span className="dataset-icon">{d.kind==='mysql'?<Database/>:d.kind==='csv'?<FileSpreadsheet/>:<HardDrive/>}</span><span className={'type-badge '+d.kind}>{d.kind.toUpperCase()}</span></div><h3>{d.name}</h3><p>{d.table_count} tables · {d.column_count} columns</p><div className="card-bottom"><span><ShieldCheck size={14}/> Read-only analysis</span><ArrowUpRight size={18}/></div></button>)}</div>:<div className="empty-state"><Database size={36}/><h2>Start with a source.</h2><p>Your uploaded data stays on this machine. MySQL and SQLite connections are queried read-only.</p><button className="primary" onClick={()=>open('upload')}>Import your first dataset <ArrowUpRight size={17}/></button></div>}
 <div className="privacy-note"><ShieldCheck size={19}/><div><strong>Local data. Separate boundaries.</strong><p>Queries use only the selected dataset. Sensitive columns are excluded, and original connected databases are never modified.</p></div></div>
 {dialog&&<Modal title={dialog==='connect'?'Connect a local database':'Import a dataset'} onClose={()=>setDialog(null)} busy={busy}><form onSubmit={submit}>
 {dialog==='connect'?<><label>Dataset name<input required maxLength={100} value={form.name} onChange={e=>update('name',e.target.value)} placeholder="Sales warehouse"/></label><label>Database type<select value={form.kind} onChange={e=>update('kind',e.target.value)}><option value="mysql">MySQL</option><option value="sqlite">SQLite file</option></select></label>
 {form.kind==='mysql'?<><div className="form-row"><label>Local host<input required value={form.host} onChange={e=>update('host',e.target.value)}/></label><label>Port<input required type="number" min={1} max={65535} value={form.port} onChange={e=>update('port',Number(e.target.value))}/></label></div><label>Database name<input required value={form.database} onChange={e=>update('database',e.target.value)}/></label><div className="form-row"><label>Read-only username<input required autoComplete="off" value={form.username} onChange={e=>update('username',e.target.value)}/></label><label>Password<input type="password" autoComplete="new-password" value={form.password} onChange={e=>update('password',e.target.value)}/></label></div><p className="field-hint">Use a dedicated SELECT-only account. Root and write-capable accounts are rejected. Credentials are encrypted in local application storage.</p></>:<><label>Absolute SQLite file path<input required value={form.path} onChange={e=>update('path',e.target.value)} placeholder="D:\Datasets\sales.sqlite"/></label><p className="field-hint">Allowed folders: {roots?.length?roots.join(', '):'None configured. Set LOCAL_FILE_ROOTS in backend/.env, then restart.'} The file is opened read-only.</p></>}</>
 :<><label>Dataset name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="Monthly sales"/></label><label className="file-drop"><Upload size={26}/><strong>{file?.name||'Choose a CSV or SQL file'}</strong><span>UTF-8 · up to 25 MB</span><input required type="file" accept=".csv,.sql" onChange={e=>{const f=e.target.files[0];setFile(f);if(f&&!name)setName(f.name.replace(/\.[^.]+$/,''))}}/></label>{file?.name.toLowerCase().endsWith('.sql')&&<label>Source SQL dialect<select value={dialect} onChange={e=>setDialect(e.target.value)}><option value="mysql">MySQL</option><option value="sqlite">SQLite</option></select></label>}<p className="field-hint">CSV requires a header. SQL imports support CREATE TABLE and INSERT VALUES, up to 10 MB. Imported files become isolated SQLite datasets; routines, views and administration statements are disabled.</p></>}
 {error&&<p className="error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setDialog(null)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Preparing dataset…':dialog==='connect'?'Connect and discover':'Import and discover'}</button></div></form></Modal>}
 </>;
}
