import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Database,MessageSquare,ShieldCheck,Layers,Activity,LogOut,ArrowRight,KeyRound,Download,FlaskConical} from 'lucide-react';
import {api} from './api';
import DatasetManager from './components/DatasetManager';
import SchemaPanel from './components/SchemaPanel';
import Analyst from './components/Analyst';
import Evaluation from './components/Evaluation';
import './styles.css';

function App(){
 const [authenticated,setAuthenticated]=useState(null),[key,setKey]=useState(''),[signing,setSigning]=useState(false),[roots,setRoots]=useState([]);
 const [health,setHealth]=useState(null),[datasets,setDatasets]=useState([]),[selected,setSelected]=useState(localStorage.getItem('lens_dataset')||''),[view,setView]=useState('datasets');
 const [result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[metrics,setMetrics]=useState(null),[history,setHistory]=useState([]);
 const dataset=datasets.find(d=>d.id===selected);
 async function reload(){const data=await api('/datasets');setDatasets(data);return data}
 async function refreshMetrics(){try{setMetrics(await api('/metrics'+(selected?'?dataset_id='+encodeURIComponent(selected):'')))}catch{}}
 useEffect(()=>{const expired=()=>{setAuthenticated(false);setDatasets([]);setResult(null)};window.addEventListener('lens-auth-expired',expired);return()=>window.removeEventListener('lens-auth-expired',expired)},[]);
 useEffect(()=>{api('/health').then(setHealth).catch(()=>{});api('/session').then(s=>{setAuthenticated(true);setRoots(s.local_file_roots);reload().catch(e=>setError(e.message))}).catch(()=>setAuthenticated(false))},[]);
 useEffect(()=>{if(authenticated)refreshMetrics()},[selected,authenticated]);
 useEffect(()=>{if(authenticated&&view==='activity')api('/history'+(selected?'?dataset_id='+encodeURIComponent(selected):'')).then(setHistory).catch(e=>setError(e.message))},[view,selected,authenticated]);
 async function login(e){e.preventDefault();setSigning(true);setError('');try{await api('/session',{method:'POST',body:{access_key:key}});setKey('');setAuthenticated(true);const s=await api('/session');setRoots(s.local_file_roots);await reload()}catch(e){setError(e.message)}finally{setSigning(false)}}
 function choose(id,next='analyst'){if(busy)return;setSelected(id);localStorage.setItem('lens_dataset',id);setResult(null);setError('');setView(next)}
 async function ask(question){if(busy||!dataset)return;setBusy(true);setError('');setResult(null);try{setResult(await api('/ask',{method:'POST',body:{dataset_id:dataset.id,question}}));refreshMetrics()}catch(e){setError(e.message);if(e.status===401)setAuthenticated(false)}finally{setBusy(false)}}
 async function logout(){try{await api('/session',{method:'DELETE'})}finally{setAuthenticated(false);setDatasets([]);setResult(null)}}
 if(authenticated===null)return <div className="boot">Connecting to your local workspace…</div>;
 if(!authenticated)return <div className="login-page"><section className="login-card"><div className="brand"><span className="brand-icon"><Layers size={25}/></span><span>local lens<small>YOUR DATA WORKSPACE</small></span></div><span className="eyebrow">PRIVATE BY DESIGN</span><h1>Your data.<br/>Your machine.</h1><p>Sign in to connect local databases, import datasets and ask questions with a local model.</p><form onSubmit={login}><label htmlFor="access-key">Workspace access key</label><input id="access-key" required type="password" autoComplete="current-password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Paste the key shown by the startup script"/><p className="field-hint">Your key is saved in backend/storage/access.key. Keep it private.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={signing}>{signing?'Signing in…':'Open workspace'}<ArrowRight size={17}/></button></form><div className="login-footer"><ShieldCheck size={17}/> Local inference · Local storage · Read-only analysis</div></section></div>;
 return <div className="workspace"><aside><a className="brand" href="/" aria-label="Local Lens home"><span className="brand-icon"><Layers size={22}/></span><span>local lens<small>DATA WORKSPACE</small></span></a><span className="nav-label">WORKSPACE</span><nav><button className={view==='datasets'?'active':''} onClick={()=>setView('datasets')}><Database size={18}/> Datasets<span className="nav-count">{datasets.length}</span></button><button className={view==='analyst'?'active':''} disabled={!dataset} onClick={()=>setView('analyst')}><MessageSquare size={18}/> Data analyst</button><button className={view==='schema'?'active':''} disabled={!dataset} onClick={()=>setView('schema')}><ShieldCheck size={18}/> Schema & access</button><button className={view==='evaluation'?'active':''} disabled={!dataset} onClick={()=>setView('evaluation')}><FlaskConical size={18}/> Harness evaluation</button><button className={view==='activity'?'active':''} onClick={()=>setView('activity')}><Activity size={18}/> Activity & feedback</button></nav><div className="sidebar-bottom"><ShieldCheck size={23}/><strong>Your data stays here.</strong><p>Local models.<br/>Read-only connections.<br/>Separate dataset boundaries.</p><button onClick={logout} disabled={busy}><LogOut size={15}/> Sign out</button></div></aside>
 <main><header><span>Workspace <span className="slash">/</span> {view==='datasets'?'Datasets':view==='schema'?'Schema & access':view==='activity'?'Activity':view==='evaluation'?'Harness evaluation':'Data analyst'}</span><div className="header-right">{!!datasets.length&&<select aria-label="Active dataset" disabled={busy} value={selected} onChange={e=>choose(e.target.value,view==='datasets'?'analyst':view)}><option value="">Select dataset</option>{datasets.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select>}<span className={'connection '+(!health?.models_ready?'warning':'')}><i/>{health?.models_ready?'Local models ready':'Check Ollama models'}</span></div></header>
 <div className="content">{error&&<div className="error" role="alert">{error}</div>}{view==='datasets'?<DatasetManager datasets={datasets} onSelect={choose} onChanged={reload} roots={roots}/>:view==='schema'&&dataset?<SchemaPanel dataset={dataset} onChanged={reload}/>:view==='analyst'&&dataset?<Analyst dataset={dataset} result={result?.dataset_id===selected?result:null} onAsk={ask} busy={busy} onRefreshMetrics={refreshMetrics}/>:view==='evaluation'&&dataset?<Evaluation dataset={dataset} datasets={datasets}/>:view==='activity'?<><div className="page-heading"><div><span className="eyebrow">OBSERVABILITY & REVIEW</span><h1>Every question has a record.</h1><p>Inspect completed requests and export Wrong-rated answers for human review.</p></div><a className="secondary" href="/api/v1/feedback/export"><Download size={17}/> Export review CSV</a></div><div className="history-list">{history.length?history.map(r=><article className="history-card" key={r.id}><div><span className={'status-badge '+r.response.status}>{r.response.status}</span><small>{r.created_at} · {r.response.latency_seconds.toFixed(1)}s</small></div><h3>{r.question}</h3><p>{r.response.answer}</p><div><span className="muted">{r.rating?'Rated '+r.rating:'Unrated'}{r.comment?' · '+r.comment:''}</span><button className="text-button" disabled={busy||!datasets.some(d=>d.id===r.dataset_id)} onClick={()=>{choose(r.dataset_id);setResult({...r.response,existing_rating:r.rating})}}>Inspect answer <ArrowRight size={14}/></button></div></article>):<div className="empty-state"><Activity size={32}/><h2>No requests yet.</h2><p>Ask a question to create an audit-linked record.</p></div>}</div></>:<div className="empty-state"><Database size={32}/><h2>Select a dataset.</h2><button className="primary" onClick={()=>setView('datasets')}>Browse datasets</button></div>}
 {view!=='datasets'&&view!=='evaluation'&&metrics&&<div className="metrics"><div><span>Rated answers</span><strong>{metrics.rated}</strong></div><div><span>User-rated accuracy</span><strong>{metrics.user_accuracy==null?'—':Math.round(metrics.user_accuracy*100)+'%'}</strong></div><div><span>Local model</span><strong className="small-stat">{health?.model||'Ollama'}</strong></div></div>}<footer><span>LOCAL LENS · YOUR DATA WORKSPACE</span><span>Generated answers can be wrong. Review the SQL and results.</span></footer></div></main>
 </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
